version: "3.8"

services:
  core:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build:
      args:
        - PROJECT_NAME=phenotyping-topological-leaf-vein
        - USER_NAME=kiwamasa
        - GROUP_NAME=MS
        - BASE_IMAGE=nvidia/cuda:11.0.3-devel-ubuntu20.04
        - PYTHON_VERSION=3.8
        - UID=${HOST_UID-1000}
        - GID=${HOST_GID-1000}
      context: ./
      dockerfile: ./Dockerfile
    tty: true
    volumes:
        - ./:/home/kiwamasa/phenotyping-topological-leaf-vein
    ports:
        - 8000:8000
