version: '3.8'
services:
  workspace:
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    build: .
    volumes:
      - ./:/workspace
    ports: 
      - "8000:8000"
    tty: true
